import {
  FusionRouter,
  generateFusionRouterConfig,
  loadFusionRouterConfigValue,
} from "../router.ts";
import {
  FixtureModelAdapter,
  FixtureSynthesisAdapter,
} from "./v0_1_fixtures.ts";

const generatedConfig = generateFusionRouterConfig({
  profile: "minimal-direct",
});
const loadedConfig = loadFusionRouterConfigValue(generatedConfig);

const adapter = new FixtureModelAdapter();
const router = new FusionRouter({
  modelAdapters: [adapter],
  synthesisAdapter: new FixtureSynthesisAdapter(),
  minSuccessfulAdapters: 1,
  routingMode: loadedConfig.routingMode,
  routingModeEnvProvider: () => undefined,
});

const result = await router.route("config generated by setup profile");

console.log(JSON.stringify(
  {
    ok: true,
    example: "setup-generated-config",
    profile: loadedConfig.setupProfile,
    routingMode: loadedConfig.routingMode,
    providerCount: loadedConfig.providers?.length ?? 0,
    adaptiveDirect: loadedConfig.adaptiveDirect,
    result,
  },
  null,
  2,
));
